Change landscape ListView into protrait
C6H5-NO2/EAxT pull request #2
Opened 2018-02-06 00:51 UTC by HurryPeng

Change landscape ListView into protrait

2018-02-06 00:52 UTC, HurryPeng commented
I can't sign yet so I didn't build the apk.

2018-02-06 12:10 UTC, C6H5-NO2 commented on app/build.gradle
> +        versionName "0.2.4"
No need to change the version name.

2018-02-06 12:13 UTC, C6H5-NO2 commented on app/src/main/java/org/szesmaker/ordermeal/AllowedList.java
> +            Toast.makeText(this, "点击列表项以更改份数", Toast.LENGTH_SHORT).show();
I personally dislike this kind of introduction. It can be omitted.

2018-02-06 12:15 UTC, C6H5-NO2 requested changes

2018-02-06 12:15 UTC, C6H5-NO2 commented on app/src/main/java/org/szesmaker/ordermeal/AllowedList.java
> +                        editor.putString("Repeater1_GvReport_" + meal_num + "_TxtNum_" + (num - 1) + "@", num + "|");
`dish_num` means which dish you've ordered while `order_num` indicates the amount. Should be 
```java
editor.putString("Repeater1_GvReport_" + meal_num + "_TxtNum_" + (position- 1) + "@", num + "|"); 
```

2018-02-06 12:15 UTC, C6H5-NO2 commented on app/src/main/res/layout/listitem.xml
> +    <TextView
Shall we delete the first TextView and sort the rest into `类别　编号　菜名　份数　单价` ? Or/And try attach a specific color to `份数` when it is available to order. This may help emphasizing.

2018-02-07 15:33 UTC, C6H5-NO2 approved these changes

2018-02-07 15:38 UTC, merged